/**
 * The MIT License
 *
 * Copyright (C) 2015 Asterios Raptis
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package io.github.astrapi69.mystic.crypt.panel.dbtree;

/**
 *
 * @author astrapi69
 */
public class MysticCryptEntryTabbedFormPanel extends javax.swing.JPanel
{

	/**
	 * Creates new form MysticCryptEntryFormPanel
	 */
	public MysticCryptEntryTabbedFormPanel()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		tbpMysticCryptEntry = new javax.swing.JTabbedPane();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
					.createSequentialGroup().addContainerGap().addComponent(tbpMysticCryptEntry,
						javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
					.addContainerGap()));
		layout
			.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
					.createSequentialGroup().addContainerGap().addComponent(tbpMysticCryptEntry,
						javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
					.addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_txtPasswordActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtPasswordActionPerformed

	private void txtUrlActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_txtUrlActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtUrlActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTabbedPane tbpMysticCryptEntry;
	// End of variables declaration//GEN-END:variables
}
