/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package io.github.astrapi69.mystic.crypt.panel.dbtree;

/**
 *
 * @author astrapi69
 */
public class PropertiesNewEntryFormPanel extends javax.swing.JPanel
{

	/**
	 * Creates new form PropertiesNewEntryFormPanel
	 */
	public PropertiesNewEntryFormPanel()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		lblKey = new javax.swing.JLabel();
		lblValue = new javax.swing.JLabel();
		btnAddEntry = new javax.swing.JButton();
		txtKey = new javax.swing.JTextField();
		txtValue = new javax.swing.JTextField();
		lblCreateNewEntry = new javax.swing.JLabel();

		lblKey.setText("Key");

		lblValue.setText("Value");

		btnAddEntry.setText("Add new entry");
		btnAddEntry.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				btnAddEntryActionPerformed(evt);
			}
		});

		txtKey.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				txtKeyActionPerformed(evt);
			}
		});

		lblCreateNewEntry.setText("Create new entry");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGroup(layout
							.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
							.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(btnAddEntry, javax.swing.GroupLayout.PREFERRED_SIZE,
									220, javax.swing.GroupLayout.PREFERRED_SIZE))
							.addGroup(layout.createSequentialGroup()
								.addGroup(layout
									.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
									.addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE,
										140, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(lblKey, javax.swing.GroupLayout.PREFERRED_SIZE,
										140, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout
									.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(txtKey).addComponent(txtValue,
										javax.swing.GroupLayout.DEFAULT_SIZE, 363,
										Short.MAX_VALUE))))
							.addGap(20, 20, 20))
						.addGroup(layout.createSequentialGroup()
							.addComponent(lblCreateNewEntry, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addGap(401, 401, 401)))));
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(110, Short.MAX_VALUE)
					.addComponent(lblCreateNewEntry).addGap(18, 18, 18)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(lblKey, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
							javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGap(18, 18, 18)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
					.addComponent(btnAddEntry).addGap(20, 20, 20)));
	}// </editor-fold>//GEN-END:initComponents

	private void btnAddEntryActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_btnAddEntryActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnAddEntryActionPerformed

	private void txtKeyActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_txtKeyActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtKeyActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAddEntry;
	private javax.swing.JLabel lblCreateNewEntry;
	private javax.swing.JLabel lblKey;
	private javax.swing.JLabel lblValue;
	private javax.swing.JTextField txtKey;
	private javax.swing.JTextField txtValue;
	// End of variables declaration//GEN-END:variables
}
