# GitHub Sponsor button configuration.
# See DONATE.md for human-readable descriptions of each channel.

github: astrapi69
liberapay: astrapi69
ko_fi: astrapi69
custom:
  - 'https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=MJ7V43GU2H386'
