######################
# project properties #
######################
projectVersion=8.1-SNAPSHOT
groupPackage=io.github.astrapi69
projectSourceCompatibility=21
projectInceptionYear=2015
projectHolderUsername=astrapi69
projectLeaderName=Asterios Raptis
slash=/
colon=:
ad=@
issuesPath=/issues
projectDescription=Demo application for the library mystic-crypt project
projectScmProviderDomain=github.com
projectScmProviderUrl=https://github.com/
projectScmGitUrlPrefix=scm:git:git:@
projectScmGitUrlSuffix=.git
projectLicenseName=MIT License
projectLicenseUrl=http://www.opensource.org/licenses/mit-license.php
projectOrganizationName=Asterios Raptis
projectOrganizationEmailName=asterios.raptis
projectOrganizationEmailDomain=gmx.net
projectOrganizationUrl=https://astrapi69.github.io/
projectLicenseDistribution=repo
projectIssueManagementSystem=GitHub
projectRepositoriesReleasesRepoUrl=https://oss.sonatype.org/service/local/staging/deploy/maven2/
projectRepositoriesSnapshotsRepoUrl=https://oss.sonatype.org/content/repositories/snapshots
projectRepositoriesUserNameKey=ossrhUsername
projectRepositoriesPasswordKey=ossrhPassword
projectRepositoriesReleasesName=Sonatype Nexus Releases
projectRepositoriesSnapshotsName=Sonatype Nexus Snapshots
projectRepositoriesMavenUrl=https://plugins.gradle.org/m2/
#####################################
# Deployment and install properties #
#####################################
############################
# IzPackInstaller property #
############################
createIzPackInstaller=false
##################
# jar properties #
##################
mainClass=io.github.astrapi69.mystic.crypt.StartMysticCryptApplication
############################
# keystore properties keys #
############################
mysticCryptStoreFile=release.mystic-crypt.store.file
mysticCryptStoreType=release.mystic-crypt.store.type
mysticCryptStorePassword=release.mystic-crypt.store.password
mysticCryptKeyPassword=release.mystic-crypt.key.password
mysticCryptKeyAlias=release.mystic-crypt.key.alias
##############################
# for deployment on sonatype #
##############################
systemProp.org.gradle.internal.publish.checksums.insecure=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.vfs.watch=true
