/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.alpharogroup.mystic.crypt.panels.checksum;

/**
 *
 * @author astrapi69
 */
public class ChecksumFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChecksumPanel
     */
    public ChecksumFormPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOpenFile = new javax.swing.JTextField();
        btnOpenFile = new javax.swing.JButton();
        lblGeneratedChecksum = new javax.swing.JLabel();
        srcGeneratedChecksum = new javax.swing.JScrollPane();
        txtGeneratedChecksum = new javax.swing.JTextArea();
        lblOwnersChecksum = new javax.swing.JLabel();
        srcOwnersChecksum = new javax.swing.JScrollPane();
        txtOwnersChecksum = new javax.swing.JTextArea();
        lblChecksumAlgorithm = new javax.swing.JLabel();
        cbxChecksumAlgorithm = new javax.swing.JComboBox<>();
        btnCompare = new javax.swing.JButton();
        txtChecksumMatchResult = new javax.swing.JTextField();

        txtOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpenFileActionPerformed(evt);
            }
        });

        btnOpenFile.setText("Open File");

        lblGeneratedChecksum.setText("Generated checksum");

        txtGeneratedChecksum.setColumns(20);
        txtGeneratedChecksum.setRows(5);
        srcGeneratedChecksum.setViewportView(txtGeneratedChecksum);

        lblOwnersChecksum.setText("Checksum from owner");

        txtOwnersChecksum.setColumns(20);
        txtOwnersChecksum.setRows(5);
        srcOwnersChecksum.setViewportView(txtOwnersChecksum);

        lblChecksumAlgorithm.setText("Checksum algorithm");

        cbxChecksumAlgorithm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCompare.setText("Compare");

        txtChecksumMatchResult.setText("Checksum Match Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeneratedChecksum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(srcGeneratedChecksum, javax.swing.GroupLayout.DEFAULT_SIZE, 1142, Short.MAX_VALUE)
                    .addComponent(srcOwnersChecksum)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChecksumAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxChecksumAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(btnCompare, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txtChecksumMatchResult))
                    .addComponent(lblOwnersChecksum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenFile)
                    .addComponent(txtOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lblGeneratedChecksum)
                .addGap(18, 18, 18)
                .addComponent(srcGeneratedChecksum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblOwnersChecksum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srcOwnersChecksum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblChecksumAlgorithm)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxChecksumAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompare)
                    .addComponent(txtChecksumMatchResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpenFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpenFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompare;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JComboBox<String> cbxChecksumAlgorithm;
    private javax.swing.JLabel lblChecksumAlgorithm;
    private javax.swing.JLabel lblGeneratedChecksum;
    private javax.swing.JLabel lblOwnersChecksum;
    private javax.swing.JScrollPane srcGeneratedChecksum;
    private javax.swing.JScrollPane srcOwnersChecksum;
    private javax.swing.JTextField txtChecksumMatchResult;
    private javax.swing.JTextArea txtGeneratedChecksum;
    private javax.swing.JTextField txtOpenFile;
    private javax.swing.JTextArea txtOwnersChecksum;
    // End of variables declaration//GEN-END:variables
}
