dependencies {

    izpack libs.izpack.ant

    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok

    implementation libs.miglayout.swing
    implementation libs.gson
    implementation libs.guava
    implementation libs.jackson.databind
    implementation libs.xstream
    implementation libs.lgood.date.picker
    implementation libs.commons.codec
    implementation libs.javahelp
    implementation libs.pf4j
    implementation libs.swing.layout
    implementation libs.jxlayer
    implementation libs.swing.worker
    implementation libs.swingx.all
    implementation libs.commons.lang3
    implementation libs.bcprov.jdk15on
    implementation libs.bcprov.ext.jdk15on
    implementation libs.bcpkix.jdk15on
    implementation libs.batik.transcoder
    implementation libs.batik.codec
    implementation libs.imgscalr.lib
    implementation libs.sqlite.jdbc
    implementation libs.auto.browser
    implementation libs.tango.icon.theme
    implementation libs.observer
    implementation libs.state
    implementation libs.eventbus
    implementation libs.visitor
    implementation libs.icon.img.extensions
    implementation libs.jremix.icon
    implementation libs.silk.icon.theme
    implementation libs.silly.collection
    implementation libs.silly.bean
    implementation libs.crypt.api
    implementation libs.crypt.data
    implementation libs.checksum.up
    implementation libs.mystic.crypt
    implementation libs.randomizer
    implementation libs.model.data
    implementation libs.throwable
    implementation libs.file.worker
    implementation libs.jobj.core
    implementation libs.silly.io
    implementation libs.swing.components
    implementation libs.swing.renderer
    implementation libs.component.model
    implementation libs.swing.base.components
    implementation libs.swing.tree.component
    implementation libs.swing.splashscreen
    implementation libs.swing.table.components
    implementation libs.menu.action
    implementation libs.net.extensions
    implementation libs.gen.tree
    implementation libs.jobj.copy
    implementation libs.data.api
    implementation libs.id.generate
    implementation libs.xml.extensions
    implementation libs.gson.extensions
    implementation libs.xstream.extensions
    implementation libs.resourcebundle.core
    implementation libs.resource.viewmodels
    implementation libs.tree.api
    implementation libs.jobj.cloner
    implementation libs.awt.extensions
    implementation libs.swing.model.components

    testImplementation libs.kee.pass.java2
    // Note: use of bundles...
    testImplementation libs.bundles.unit.testing
    testRuntimeOnly libs.junit.platform.launcher
}
