/**
 * The MIT License
 *
 * Copyright (C) 2015 Asterios Raptis
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package io.github.astrapi69.mystic.crypt.panel.certificate;

import javax.swing.*;

import io.github.astrapi69.crypt.data.model.X509CertificateV3Info;
import io.github.astrapi69.model.BaseModel;
import io.github.astrapi69.model.LambdaModel;
import io.github.astrapi69.model.api.IModel;
import io.github.astrapi69.swing.base.BasePanel;
import io.github.astrapi69.swing.model.combobox.GenericComboBoxModel;
import io.github.astrapi69.swing.model.component.JMComboBox;
import io.github.astrapi69.swing.model.component.JMTextArea;
import io.github.astrapi69.swing.model.component.JMTextField;
import lombok.Getter;

/**
 *
 * @author astrapi69
 */
@Getter
public class CertificatePanel extends BasePanel<X509CertificateV3Info>
{

	/**
	 * The Constant serialVersionUID.
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * The algorithms the fingerprint can be taken with, as the form was designed with them
	 */
	private static final String[] FINGERPRINT_ALGORITHMS = { "Item 1", "Item 2", "Item 3",
			"Item 4" };

	/** What this panel shows about the certificate; every component below writes into it */
	private transient CertificatePanelModel certificateModel;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JMComboBox<String, GenericComboBoxModel<String>> cmbFingerprintAlgorithm;

	private JLabel lblFingerprint;

	private JLabel lblIssuedBy;


	private JLabel lblIssuedTo;
	private JLabel lblPublicKey;
	private JLabel lblSerialNumber;
	private JLabel lblSignatureAlgorithm;
	private JLabel lblValidFrom;
	private JLabel lblValidUntil;
	private JLabel lblVersion;
	private JScrollPane scrPublicKey;
	private JMTextField txtFingerprint;
	private JMTextField txtIssuedBy;
	private JMTextField txtIssuedTo;
	private JMTextArea txtPublicKey;
	private JMTextField txtSerialNumber;
	private JMTextField txtSignatureAlgorithm;
	private JMTextField txtValidFrom;
	private JMTextField txtValidUntil;
	private JMTextField txtVersion;

	// End of variables declaration//GEN-END:variables

	public CertificatePanel()
	{
		this(BaseModel.of(X509CertificateV3Info.builder().build()));
	}

	public CertificatePanel(final IModel<X509CertificateV3Info> model)
	{
		super(model);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

	}// </editor-fold>//GEN-END:initComponents


	@Override
	protected void onInitializeComponents()
	{
		super.onInitializeComponents();
		certificateModel = new CertificatePanelModel();
		// the combo starts on the first algorithm it offers, so the model carries what is shown
		certificateModel.setFingerprintAlgorithm(FINGERPRINT_ALGORITHMS[0]);
		lblIssuedTo = new JLabel();
		txtIssuedTo = new JMTextField();
		lblIssuedBy = new JLabel();
		txtIssuedBy = new JMTextField();
		lblVersion = new JLabel();
		txtVersion = new JMTextField();
		lblSerialNumber = new JLabel();
		txtSerialNumber = new JMTextField();
		lblValidFrom = new JLabel();
		txtValidUntil = new JMTextField();
		txtValidFrom = new JMTextField();
		lblValidUntil = new JLabel();
		lblSignatureAlgorithm = new JLabel();
		txtFingerprint = new JMTextField();
		lblFingerprint = new JLabel();
		txtSignatureAlgorithm = new JMTextField();
		// the combo box model starts on the algorithm the model holds, so the selection the combo
		// box remembers and the one the model carries cannot drift apart
		cmbFingerprintAlgorithm = new JMComboBox<>(new GenericComboBoxModel<>(
			FINGERPRINT_ALGORITHMS, certificateModel.getFingerprintAlgorithm()));
		lblPublicKey = new JLabel();
		scrPublicKey = new JScrollPane();
		txtPublicKey = new JMTextArea();

		lblIssuedTo.setText("Issued to");

		txtIssuedTo.setToolTipText("");

		lblIssuedBy.setText("Issued by");

		txtIssuedBy.setToolTipText("");

		lblVersion.setText("Version");

		lblSerialNumber.setText("Serial number");

		lblValidFrom.setText("Valid from");

		lblValidUntil.setText("Valid until");

		lblSignatureAlgorithm.setText("Signature algorithm");

		lblFingerprint.setText("Fingerprint");

		lblPublicKey.setText("Public key");

		txtPublicKey.setColumns(20);
		txtPublicKey.setRows(5);
		scrPublicKey.setViewportView(txtPublicKey);

		bindComponents();
	}

	/**
	 * Binds every component to {@link CertificatePanelModel}, so that each edit lands in the model
	 * and the model is what the panel state is read from - the components carry the values the
	 * model already holds
	 */
	protected void bindComponents()
	{
		txtIssuedTo.setPropertyModel(
			LambdaModel.of(certificateModel::getIssuedTo, certificateModel::setIssuedTo));
		txtIssuedBy.setPropertyModel(
			LambdaModel.of(certificateModel::getIssuedBy, certificateModel::setIssuedBy));
		txtVersion.setPropertyModel(
			LambdaModel.of(certificateModel::getVersion, certificateModel::setVersion));
		txtSerialNumber.setPropertyModel(
			LambdaModel.of(certificateModel::getSerialNumber, certificateModel::setSerialNumber));
		txtValidFrom.setPropertyModel(
			LambdaModel.of(certificateModel::getValidFrom, certificateModel::setValidFrom));
		txtValidUntil.setPropertyModel(
			LambdaModel.of(certificateModel::getValidUntil, certificateModel::setValidUntil));
		txtSignatureAlgorithm.setPropertyModel(LambdaModel
			.of(certificateModel::getSignatureAlgorithm, certificateModel::setSignatureAlgorithm));
		txtFingerprint.setPropertyModel(
			LambdaModel.of(certificateModel::getFingerprint, certificateModel::setFingerprint));
		cmbFingerprintAlgorithm.setPropertyModel(LambdaModel.of(
			certificateModel::getFingerprintAlgorithm, certificateModel::setFingerprintAlgorithm));
		txtPublicKey.setPropertyModel(
			LambdaModel.of(certificateModel::getPublicKey, certificateModel::setPublicKey));
	}

	@Override
	protected void onInitializeLayout()
	{
		super.onInitializeLayout();
		onInitializeGroupLayout();
	}

	protected void onInitializeGroupLayout()
	{
		GroupLayout layout = new GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup().addGap(63, 63, 63)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
					.addComponent(lblPublicKey, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
					.addComponent(lblFingerprint, GroupLayout.DEFAULT_SIZE,
						GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(lblSignatureAlgorithm, GroupLayout.DEFAULT_SIZE,
						GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(lblValidFrom, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
					.addComponent(lblSerialNumber, GroupLayout.DEFAULT_SIZE,
						GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(lblVersion, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
					.addComponent(lblIssuedBy, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
					.addComponent(lblIssuedTo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
					.addComponent(lblValidUntil, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE))
				.addGap(47, 47, 47)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
					.addComponent(txtIssuedTo)
					.addComponent(txtIssuedBy, GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
					.addComponent(txtVersion, GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
					.addComponent(txtSerialNumber).addComponent(txtValidUntil)
					.addComponent(txtValidFrom).addComponent(txtSignatureAlgorithm)
					.addGroup(layout.createSequentialGroup()
						.addComponent(txtFingerprint, GroupLayout.PREFERRED_SIZE, 309,
							GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(cmbFingerprintAlgorithm, 0,
							GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					.addComponent(scrPublicKey))
				.addContainerGap(82, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup().addGap(38, 38, 38)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(lblIssuedTo).addComponent(txtIssuedTo, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(lblIssuedBy).addComponent(txtIssuedBy, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(lblVersion).addComponent(txtVersion, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(lblSerialNumber).addComponent(txtSerialNumber,
						GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE))
				.addGap(17, 17, 17)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
					.addComponent(lblValidFrom).addComponent(txtValidFrom,
						GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(txtValidUntil, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addComponent(lblValidUntil))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(lblSignatureAlgorithm).addComponent(txtSignatureAlgorithm,
						GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					.addComponent(lblFingerprint)
					.addComponent(txtFingerprint, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addComponent(cmbFingerprintAlgorithm, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
					.addComponent(lblPublicKey).addComponent(scrPublicKey,
						GroupLayout.PREFERRED_SIZE, 280, GroupLayout.PREFERRED_SIZE))
				.addContainerGap(56, Short.MAX_VALUE)));
	}

}
